name: AllInOne CICD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download ANTLR
        run: |
          curl -o antlr-4.13.0-complete.jar https://www.antlr.org/download/antlr-4.13.0-complete.jar

      - name: Search and Generate Lexer and Parser for all .g4 files
        run: |
          echo "Searching for .g4 files in the entire project..."
          files=$(find . -type f -name "*.g4")
          if [ -z "$files" ]; then
            echo "No .g4 files found. Exiting..."
            exit 1
          fi
          echo "Found .g4 files:"
          for file in $files; do
            echo "Processing $file..."
            java -jar antlr-4.13.0-complete.jar -Dlanguage=Java -visitor -listener -package com.example.grammar "$file"
          done

      - name: Build Application (Gradle)
        run: ./gradlew build --no-daemon

      - name: Test Application (Gradle)
        run: ./gradlew test --no-daemon

      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%h-%d-%m_%Y-%M-%S')" >> $GITHUB_ENV

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}-${{ env.TIMESTAMP }}
          path: build/reports/tests/test

  license-and-header-check:
    name: License and Header Check
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ScanCode Toolkit
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install scancode-toolkit

      - name: Find and scan .g4 files
        run: |
          mkdir -p $GITHUB_WORKSPACE/scancode_results
          find $GITHUB_WORKSPACE -name "*.g4" | tee g4_files.txt | xargs -I {} scancode -cl --json-pp "$GITHUB_WORKSPACE/scancode_results/$(basename {}).json" {}

      - name: Run license and header check script
        run: python3 scripts/license_check.py

      - name: Upload license and header check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-and-header-check-report
          path: license_and_header_check_report.json

  docker-steps:
    name: Docker Operations
    runs-on: ubuntu-latest
    needs: license-and-header-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.TOKEN_DOCKER_TESTMITGRADLE2 }}
        run: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sysmlv2parser:latest .

      - name: Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/sysmlv2parser:latest ${{ secrets.DOCKER_USERNAME }}/sysmlv2parser:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sysmlv2parser:latest

      - name: Verify Docker Image
        run: |
          echo "Image pushed to DockerHub: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/sysmlv2parser:latest"
