name: Fossology License Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fossology:
    runs-on: ubuntu-latest
    container:
      image: fossology/fossology:scanner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Fossology Scanner
        run: |
          mkdir -p ./results
          /bin/fossologyscanner repo nomos ojo copyright keyword -o ./results

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-result
          path: ./results

      - name: Download Scan Results (Optional)
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: scan-result



