name: License Compliance with FOSSology

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fossology-scan:
    name: Run FOSSology Scan
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: fossy
          POSTGRES_PASSWORD: fossy
          POSTGRES_DB: fossology
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U fossy -d fossology"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run FOSSology Docker Container
        run: |
          docker run --rm \
         --network host \
          -e "FOSSOLOGY_DB_USER=fossy" \
          -e "FOSSOLOGY_DB_PASSWORD=fossy" \
          -e "FOSSOLOGY_DB_NAME=fossology" \
          -e "FOSSOLOGY_DB_HOST=localhost" \
          fossology/fossology \
          fossology --upload-dir /fossology_input --analysis --report
  

      - name: Save SPDX Report
        run: |
          mkdir -p reports
          mv ${{ github.workspace }}/spdx2/* reports/

      - name: Upload SPDX Report
        uses: actions/upload-artifact@v4
        with:
          name: fossology-spdx-report
          path: reports/
