name: Fossology License Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  fossology:
    runs-on: ubuntu-latest
    container:
      image: fossology/fossology:scanner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set GitHub Token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV


      - name: Run Fossology Scanner
        run: |
          mkdir -p ./results
          /bin/fossologyscanner repo nomos ojo copyright keyword > ./results/scan-report.txt


      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-result
          path: ./results

      - name: Download Scan Results (Optional)
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: scan-result



