name: License and Header Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license_and_header_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ScanCode Toolkit
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install scancode-toolkit

      - name: Find all .g4 files
        id: find_g4_files
        run: |
          find $GITHUB_WORKSPACE -name "*.g4" > g4_files.txt
        shell: bash

      - name: Run ScanCode Toolkit on .g4 files
        run: |
          mkdir -p scancode_results
          while IFS= read -r file; do
            scancode --json-pp "scancode_results/$(basename "$file").json" "$file"
          done < g4_files.txt
        shell: bash

      - name: Run license and header check
        run: |
          python3 scripts/license_check.py
        env:
          G4_FILES_LIST: ${{ steps.find_g4_files.outputs.g4_files }}
          SCANCODE_RESULTS_DIR: $GITHUB_WORKSPACE/scancode_results

      - name: Upload ScanCode reports
        uses: actions/upload-artifact@v4
        with:
          name: scancode-reports
          path: scancode_results/

      - name: Upload g4 files list
        uses: actions/upload-artifact@v4
        with:
          name: g4-files-list
          path: g4_files.txt
